[package]
name = "sevend"
version = "0.1.0"
authors = ["Sullome <sullome@yandex.com>"]

[dependencies]
rand     = "0.4"

[dependencies.rusqlite]
version = "0.13.0"
features = ["blob"]

[dependencies.sdl2]
version = "0.31.0"
features = ["image"]
